layout_spectrum: 0.3227612
color:
  saturation: 0.2826261
  lightness: 0.1011499
  brandStrength: 0.505597
  brandColors:
    - '#F3F3F3'
    - '#FFBB00'
    - '#6F5FB8'
    - '#EB113E'
    - '#BDBDBB'
  rhythmicContrast: 0.2947761
typography_spectrum: 0.1711754
name: AndreKelso
